<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Stupid responder');
echo $this->doctype(); 
echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/main.css'); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
  </head>
  <body>
    <div id="content">
      <div id="header">
        Привет! Вы можете
          <a href=<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>>попасть на главную</a>
          или
          <a href=<?php echo $this->url(array('controller' => 'index', 'action' => 'register')); ?>>зарегистрироваться</a>
      </div>
       <h1><?php echo $this->escape($this->title); ?></h1>
       <?php echo $this->layout()->content; ?>
      <div id="footer">

      </div>
    </div>
  </body>
</html>
